apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels: { app: demo-app }
spec:
  replicas: 3
  selector:
    matchLabels: { app: demo-app }
  template:
    metadata:
      labels: { app: demo-app }
    spec:
      containers:
        - name: demo-app
          image: demo-app:0.1.0   # Nuestra imagen
          imagePullPolicy: IfNotPresent # Para que k8s use la imagen local en vez de la de internet
          ports:
            - containerPort: 8000 # Cambiamos el puerto al 8000